/* Name:-Prachi Parab Component:-PieChart report
         End LineNo:-1 to 105 Date:-10/07 */

import React, { useEffect, useState } from "react";
import "../Reports/PieChartReport.css";
import { Pie } from "react-chartjs-2";
import { Chart, ArcElement, Tooltip } from "chart.js";
import { getFormattedDateTime } from "../EmployeeSection/getFormattedDateTime";
import { getEmployeNameFromApiReusable } from "../HandlerFunctions/getEmployeNameFromApiReusable";

Chart.register(Tooltip);
Chart.register(ArcElement);

const PieChart = ({
  data,
  userName,
  finalStartDatePropState,
  finalEndDatePropState,
  selectedRole,
  selectedIds,
}) => {
  console.log(data);
  const [currentDate, setCurrentDate] = useState("");
  useEffect(() => {
    setCurrentDate(getFormattedDateTime());
  }, []);
  const filteredData = data.filter(item => item.category !== "TotalCandidates");
  const categories = filteredData.map((item) => item.category);
  const counts = filteredData.map((item) => item.count);

  const predefinedColors = [
    "rgba(160, 82, 45, 0.7)",
    "#ffc3ba",
    "#B4B4B8",
    "rgba(127,101,77,0.8)",
    "#004c4c",
    "#ff8080",
    "rgba(117,118,118)",
    "#bf4545",
    "#ffded9",
    "rgba(127,108,84,0.5)",
    "#982828",
    "#f8cec8",
    "#008080",
    "rgba(168,118,118, 0.9)",
    "#EF9C66",
    "rgba(255,213,175,0.7)",
    "#6b0b0b",
  ];

  const backgroundColor = categories.map(
    (_, index) => predefinedColors[index % predefinedColors.length]
  );

  const chartData = {
    labels: categories,
    datasets: [
      {
        label: "Counts",
        data: counts,
        backgroundColor,
        borderWidth: 2,
        hoverOffset: 5,
      },
    ],
  };


  const options = {
    plugins: {
      title: {
        display: true,
        text: "Count Tracker - Candidates Categories vs Count",
      },
    },

  };

  const [employeeNames, setEmployeeNames] = useState([]);
  useEffect(() => {
    const fetchNames = async () => {
      if (selectedIds?.length > 0) {
        const names = await Promise.all(
          selectedIds.map((id) => getEmployeNameFromApiReusable(id, selectedRole))
        );
        setEmployeeNames(names);
      }
    };
    fetchNames();
  }, [selectedIds, selectedRole]);
  return (
    <>
      <div className="mainChartContainer setwidthacordingtoadjustchartsclass" >
      

        <div className="subdivforcharts">
          <div className="piecontainer">
          <p style={{
            marginBottom:"50px",
            fontWeight:"bold"
          }}
          className="newClassnameForHideAndDisplay"
          >
    Report Generated By {userName} Of {selectedRole}
    {(selectedIds?.length > 1 && selectedRole !== "Recruiters") ? <span>s</span> : null}{" "}
    {employeeNames.map((name, index) => (
      <span key={selectedIds[index]}>{index+1} : {name} {index === selectedIds.length - 1 ? " " : ","} </span>
    ))}
  </p>

            <Pie className="newsahilcanvas" data={chartData} options={options}/>
          </div>

          {/* <div className="newIndexDiv">
            <ul className="newUlListDisplayGrid">
              {categories.map((category, index) => (
                <li key={index} className="listOfIndex">
                  <div
                    style={{
                      width: "20px",
                      height: "20px",
                      backgroundColor:
                        predefinedColors[index % predefinedColors.length],
                      marginRight: "10px",
                    }}
                  ></div>
                  <span>{category}</span>
                </li>
              ))}
            </ul>
          </div> */}
        </div>
      </div>
    </>
  );
};
export default PieChart;

